### ISSUE TITLE
PG::UndefinedObject - ERROR:  unrecognized configuration parameter "logidze.disabled"

### ISSUE THREAD

**Issue by devilankur18** [palkan/logidze#10]
I am using rails 5.0.0, with production and development server.

When I take a pull from production server to my local server, the configuration for logidze.disabled is always missing probably due to role specific config are ignored during exporting/importing.

I even add a rake a task which will set this config variable, but still, I am facing issues in development, whenever I am updating any model who have logidze installed.

```
namespace :db_sync do
  desc "Post import task"
  task :post_import do
    ActiveRecord::Base.connection.execute("SET logidze.disabled TO off; select current_setting('logidze.disabled')")
  end
end
```

Any suggestions ?

**Comment by palkan** [comment]
Please, try `SHOW logidze.disabled;` in psql console (or from Ruby, it doesn't matter).

If it raises the same error then you haven't set this variable. It is set by _install_ migration for current database (https://github.com/palkan/logidze/blob/master/lib/generators/logidze/install/templates/migration.rb.erb#L6).

**Comment by devilankur18** [comment]
@palkan Yep, its its working same as other similar queries. And still in my rails application I am facing the same error. Is that has to anything with transactions or activerecord connection pool ?

**Comment by devilankur18** [comment]
I think the issue was facing was due to different reason, and its seems to be fixed for me, not related to the gem. When I upgraded to 9.5 old postgres was still running and accepting connections, so it causing mismatches.

**Comment by sharshenov** [comment]
Rails 5.0.0.1
Logidze 0.3.0
Postgres 9.5.4 (gem pg 0.18.4)

ActiveRecord is configured to store database structure in sql format (to be able to track stored procedures in schema dump)
```
module Dashboard
  class Application < Rails::Application
    config.active_record.schema_format = :sql
  end
end
```

Logidze initial migration sets both `logidze.disabled` and `logidze.responsible` variables. But structure.sql doesn't include them(only default ones like `SET client_encoding = 'UTF8'`). So `rake db:reset` task is not able to set logidze variables.

Is it the same issue?

**Comment by palkan** [comment]
@sharshenov Have you checked `SHOW logidze.disabled;`?

**Comment by sharshenov** [comment]
Sure. When migrations are forced to run:
```bash
rake db:drop db:create db:migrate
rails dbconsole
```
```sql
SHOW logidze.disabled;
 logidze.disabled
------------------
 off
(1 row)
```

When database schema is loaded from structure.sql:
```bash
rake db:reset
rails dbconsole
```
```sql
SHOW logidze.disabled;
ERROR:  unrecognized configuration parameter "logidze.disabled
```

**Comment by palkan** [comment]
I did some investigation and found out the following: `db:structure:dump` uses `pg_dump` to generate `structure.sql`. Unfortunately, `pg_dump` doesn't include user-defined DB variables, because, from the PostgreSQL point of view, there are _cluster_-level.
And there is another command – [`pg_dump_all`](https://www.postgresql.org/docs/9.5/static/app-pg-dumpall.html) – for dumping the whole cluster which includes such variables.

**Comment by ribanez7** [comment]
I jump into this issue when I dump (pg_dump) a production database and restore (pg_restore) it in development. My solution to this has been to execute, after the restore, the following task (and then restart the server, of course):

```ruby
namespace :logidze do
  desc 'Post restore task'
  task post_restore: :environment do
    logidze_variables = <<-SQL
      DO $$
        BEGIN
        EXECUTE 'ALTER DATABASE ' || quote_ident(current_database()) || ' SET logidze.disabled=' || quote_literal('');
        EXECUTE 'ALTER DATABASE ' || quote_ident(current_database()) || ' SET logidze.responsible=' || quote_literal('');
        END;
      $$
      LANGUAGE plpgsql;
    SQL
    ActiveRecord::Base.connection.execute(logidze_variables)
  end
end
```
My routine, when restoring a db, is then:

```bash
$ createdb app_name_development
$ pg_restore -O -c -j 10 -h localhost -p 5432 -d app_name_development /path/to/production/pg_dump
$ rails logidze:post_restore
```
So just in case someone has the same problem, this way it works for me.
