### ISSUE TITLE
Has many through support

### ISSUE THREAD

**Issue by davidpatters0n** [palkan/logidze#120]
Following up from: #45 is there any plans for adding support for has_many through associations?

**Comment by palkan** [comment]
> any plans for adding support for has_many through associations?

Is this not supported already? Although we don't have tests for that (yet), the implementation doesn't check for any particular association types: https://github.com/palkan/logidze/blob/ffa0f793cb9c6fab96fa67a285341ca9aaa7ded8/lib/logidze/model.rb#L191-L197 (`has_many through:` is a `CollectionAssociation`)

**Comment by davidpatters0n** [comment]
Thanks.
