### ISSUE TITLE
Question: do limits not apply to records with more than X log_data entries?

### ISSUE THREAD

**Issue by jonknapp** [palkan/logidze#132]
Looking at the migration that is generated, it looks like row collapsing only occurs when the number of log entries exactly matches the set row limit.

For example, if a limit of 30 is set, any record that has less than 30 `log_data` entries would work as expected; however, if a record already has 31+ entries, it would not collapse future entries and instead continues to add new entries as if there were no limit.

Is this a good enhancement opportunity?

**Comment by palkan** [comment]
That's a good catch.

> Is this a good enhancement opportunity?

Sure! Feel free to open a PR.
