### ISSUE TITLE
Conflict with multiple ActiveStorage local file uploads

### ISSUE THREAD

**Issue by archonic** [palkan/logidze#137]
### Tell us about your environment

**Ruby Version:**
2.6.1

**Rails Version:**
6.0.0

**PostgreSQL Version:**
9.6.15

**Logidze Version:**
0.10.0

### What did you do?
```
Logidze.without_logging do
  resource = Resource.new
  resource.images.attach(
    io: File.open( "example_file_1.jpg" )
  )
  resource.images.attach(
    io: File.open( "example_file_2.jpg" )
  )
  resource.save
end
```

### What did you expect to happen?
I would expect both uploads to work and be present after the `without_logging` block.

### What actually happened?
Despite appearing to succeed at every step, only the last image will be present. The attachment data appears to be intact but the uploaded file is missing from disk (for local dev) and the same problem happens with cloud storage configured. I don't know how it's doing that but I narrowed down a bug to the without_logging block.

Update: Same thing happens with an ActiveRecord transaction block. The issue may be with ActiveStorage.

**Comment by archonic** [comment]
I'm going to close this as I've confirmed it's an issue between ActiveRecord and ActiveStorage.

**Comment by jasonivers** [comment]
> I'm going to close this as I've confirmed it's an issue between ActiveRecord and ActiveStorage.

I'm experiencing this issue.  Did you figure out a way to make it work?  You said you confirmed it was an issue between ActiveRecord and ActiveStorage, but how did you make it work?
