### ISSUE TITLE
Testing JSON response

### ISSUE THREAD

**Issue by christianrolle** [palkan/logidze#138]
### Tell us about your environment

**Ruby Version:**
2.6.3p62
**Rails Version:**
6.0.0
**PostgreSQL Version:**
10.10
**Logidze Version:**
0.10.0
### What did you do?
Test a datatable-endpoint (JSON response)
### What did you expect to happen?
I expected the test to resturn with status 200
### What actually happened?
It failed internally with following stacktrace:

(pry) output error: #<ActiveModel::MissingAttributeError: ActiveModel::MissingAttributeError>
/home/christian/.rvm/gems/ruby-2.6.3@fps/gems/logidze-0.10.0/lib/logidze/ignore_log_data/missing_attribute_patch.rb:11:in `log_data'
/home/christian/.rvm/gems/ruby-2.6.3@fps/gems/activemodel-6.0.0/lib/active_model/serialization.rb:137:in `block in serializable_hash'
/home/christian/.rvm/gems/ruby-2.6.3@fps/gems/activemodel-6.0.0/lib/active_model/serialization.rb:137:in `each'
/home/christian/.rvm/gems/ruby-2.6.3@fps/gems/activemodel-6.0.0/lib/active_model/serialization.rb:137:in `serializable_hash'
/home/christian/.rvm/gems/ruby-2.6.3@fps/gems/activerecord-6.0.0/lib/active_record/serialization.rb:19:in `serializable_hash'
/home/christian/.rvm/gems/ruby-2.6.3@fps/bundler/gems/devise-732e54ed16d0/lib/devise/models/authenticatable.rb:115:in `serializable_hash'
/home/christian/.rvm/gems/ruby-2.6.3@fps/bundler/gems/devise-732e54ed16d0/lib/devise/models/authenticatable.rb:121:in `inspect'
/home/christian/.rvm/gems/ruby-2.6.3@fps/gems/awesome_print-1.8.0/lib/awesome_print/formatter.rb:50:in `inspect'
/home/christian/.rvm/gems/ruby-2.6.3@fps/gems/awesome_print-1.8.0/lib/awesome_print/formatter.rb:50:in `inspect'
/home/christian/.rvm/gems/ruby-2.6.3@fps/gems/awesome_print-1.8.0/lib/awesome_print/formatter.rb:50:in `inspect'
/home/christian/.rvm/gems/ruby-2.6.3@fps/gems/awesome_print-1.8.0/lib/awesome_print/formatter.rb:50:in `inspect'
/home/christian/.rvm/gems/ruby-2.6.3@fps/gems/awesome_print-1.8.0/lib/awesome_print/formatter.rb:50:in `awesome_self'
/home/christian/.rvm/gems/ruby-2.6.3@fps/gems/awesome_print-1.8.0/lib/awesome_print/formatter.rb:28:in `format'
/home/christian/.rvm/gems/ruby-2.6.3@fps/gems/awesome_print-1.8.0/lib/awesome_print/inspector.rb:115:in `unnested'
/home/christian/.rvm/gems/ruby-2.6.3@fps/gems/awesome_print-1.8.0/lib/awesome_print/inspector.rb:74:in `awesome'
/home/christian/.rvm/gems/ruby-2.6.3@fps/gems/awesome_print-1.8.0/lib/awesome_print/core_ext/kernel.rb:10:in `ai'
/home/christian/work/evopark/fps_rails/.pryrc:3:in `block in __pry__'
/home/christian/.rvm/gems/ruby-2.6.3@fps/gems/pry-0.12.2/lib/pry/pry_instance.rb:399:in `show_result'
/home/christian/.rvm/gems/ruby-2.6.3@fps/gems/pry-0.12.2/lib/pry/pry_instance.rb:368:in `block in handle_line'
/home/christian/.rvm/gems/ruby-2.6.3@fps/gems/pry-0.12.2/lib/pry/pry_class.rb:401:in `critical_section'
/home/christian/.rvm/gems/ruby-2.6.3@fps/gems/pry-0.12.2/lib/pry/pry_instance.rb:367:in `handle_line'
/home/christian/.rvm/gems/ruby-2.6.3@fps/gems/pry-0.12.2/lib/pry/pry_instance.rb:274:in `block (2 levels) in eval'
/home/christian/.rvm/gems/ruby-2.6.3@fps/gems/pry-0.12.2/lib/pry/pry_instance.rb:273:in `catch'
/home/christian/.rvm/gems/ruby-2.6.3@fps/gems/pry-0.12.2/lib/pry/pry_instance.rb:273:in `block in eval'
/home/christian/.rvm/gems/ruby-2.6.3@fps/gems/pry-0.12.2/lib/pry/pry_instance.rb:272:in `catch'
/home/christian/.rvm/gems/ruby-2.6.3@fps/gems/pry-0.12.2/lib/pry/pry_instance.rb:272:in `eval'
/home/christian/.rvm/gems/ruby-2.6.3@fps/gems/pry-0.12.2/lib/pry/repl.rb:77:in `block in repl'
/home/christian/.rvm/gems/ruby-2.6.3@fps/gems/pry-0.12.2/lib/pry/repl.rb:67:in `loop'
/home/christian/.rvm/gems/ruby-2.6.3@fps/gems/pry-0.12.2/lib/pry/repl.rb:67:in `repl'
/home/christian/.rvm/gems/ruby-2.6.3@fps/gems/pry-0.12.2/lib/pry/repl.rb:38:in `block in start'
/home/christian/.rvm/gems/ruby-2.6.3@fps/gems/pry-0.12.2/lib/pry/input_lock.rb:59:in `__with_ownership'
/home/christian/.rvm/gems/ruby-2.6.3@fps/gems/pry-0.12.2/lib/pry/input_lock.rb:77:in `with_ownership'
/home/christian/.rvm/gems/ruby-2.6.3@fps/gems/pry-0.12.2/lib/pry/repl.rb:38:in `start'
/home/christian/.rvm/gems/ruby-2.6.3@fps/gems/pry-0.12.2/lib/pry/repl.rb:13:in `start'
/home/christian/.rvm/gems/ruby-2.6.3@fps/gems/pry-0.12.2/lib/pry/pry_class.rb:200:in `start'
/home/christian/.rvm/gems/ruby-2.6.3@fps/gems/pry-byebug-3.7.0/lib/byebug/processors/pry_processor.rb:117:in `block in resume_pry'
/home/christian/.rvm/gems/ruby-2.6.3@fps/gems/pry-byebug-3.7.0/lib/byebug/processors/pry_processor.rb:30:in `block (2 levels) in run'
/home/christian/.rvm/gems/ruby-2.6.3@fps/gems/byebug-11.0.1/lib/byebug/helpers/eval.rb:94:in `allowing_other_threads'
/home/christian/.rvm/gems/ruby-2.6.3@fps/gems/pry-byebug-3.7.0/lib/byebug/processors/pry_processor.rb:30:in `block in run'
/home/christian/.rvm/gems/ruby-2.6.3@fps/gems/pry-byebug-3.7.0/lib/byebug/processors/pry_processor.rb:29:in `catch'
/home/christian/.rvm/gems/ruby-2.6.3@fps/gems/pry-byebug-3.7.0/lib/byebug/processors/pry_processor.rb:29:in `run'
/home/christian/.rvm/gems/ruby-2.6.3@fps/gems/pry-byebug-3.7.0/lib/byebug/processors/pry_processor.rb:113:in `resume_pry'
/home/christian/.rvm/gems/ruby-2.6.3@fps/gems/pry-byebug-3.7.0/lib/byebug/processors/pry_processor.rb:65:in `at_line'
/home/christian/.rvm/gems/ruby-2.6.3@fps/gems/byebug-11.0.1/lib/byebug/context.rb:98:in `at_line'
/home/christian/work/evopark/fps_rails/spec/requests/admin/media/index_spec.rb:27:in `block (3 levels) in <main>'

**Comment by palkan** [comment]
Thanks for the report!

This is likely related to the regression introduced in 0.10.0 and fixed in 0.11.0 (see [this thread](https://github.com/palkan/logidze/issues/127), for example).
Please, try to upgrade the gem and see whether the error disappears.

**Comment by christianrolle** [comment]
@palkan Thank's for the version 0.11.0.
It solved the issue.
