### ISSUE TITLE
Enable in Controller around action only

### ISSUE THREAD

**Issue by tkoenig** [palkan/logidze#141]
I see that `Logidze.with_log_data` was removed in the latest release.

Is there any other way to do this? And why was it removed?

**Comment by palkan** [comment]
>  And why was it removed?

Check this thread https://github.com/palkan/logidze/issues/127 and PR https://github.com/palkan/logidze/pull/128.

tl;dr It was broken, and there is no good alternative.

> Is there any other way to do this? 

We still have `Model.with_log_data`.

**Comment by tkoenig** [comment]
Thanks for your quick response @palkan.

But there is no way with `Model.with_log_data` to do `@project.owner.at(time: ...)`* in a view right?

*(project has_one :owner)

**Comment by palkan** [comment]
There is a way:

```ruby
class Project < AR
  # smth like this
  has_one :owner_with_log_data, -> { with_log_data }, class_name: "Owner"
end

@project.owner_with_log_data.at(time: ts)
```

Or `@project.owner.tap(&:reload_log_data).at(...)`. Though this approach is prone to N+1

**Comment by tkoenig** [comment]
@palkan thanks for the feedback, this sounds reasonable for me!
