### ISSUE TITLE
responsible_id not being populated

### ISSUE THREAD

**Issue by ianpetzer** [palkan/logidze#142]
**Ruby Version:**
ruby 2.4.5p335 (2018-10-18 revision 65137) [x86_64-darwin18]

**Rails Version:**
Rails 4.2.11.1

**PostgreSQL Version:**
11
pg gem (0.17.1)

**Logidze Version:**
was on 0.9.0 and tried 0.11.0 as well

### What did you do?

Added this to my controller:

      around_action :set_logidze_responsible
      def set_logidze_responsible(&block)
        Logidze.with_responsible(current_user&.id, &block) 
      end

### What did you expect to happen?

the responsible_id to be populated on versions

### What actually happened?

The responsible_id is always nil.

When I make a request to the controller I see the following in the logs:
   (1.7ms)  BEGIN
   (1.1ms)  SET LOCAL logidze.meta = '{"_r":430}';
and at the end
   (0.7ms)  SET LOCAL logidze.meta TO DEFAULT;
   (0.7ms)  COMMIT

However, the responsible id is not populated

I used byebug debugger to check that current_user&.id actually has a value when         Logidze.with_responsible is called, and the log data contains revision histories but no responsible_id

Any ideas on what I can do to try and get this to start populating?

**Comment by palkan** [comment]
Is 0.9 the first version you tried or you started using Logidze earlier? That could be an out-of-date `logidze_xyz` function.

If it's not the case, could you do the following:
- figure out which model is created/updated
- add `after_save` callback with the following code:

```ruby
p "LOGIDZE META: #{ActiveRecord::Base.connection.execute("SELECT current_setting('logidze.meta');").values.first}
```

Do you use multiple threads per request or multiple DBs by any chance?

**Comment by ianpetzer** [comment]
Hi,

I started with an earlier version than 0.9 and I'm pretty sure it used to work at some point. I don't look through revisions very often and I only noticed today. Could've been like this for months.

How can I check for an out of date `logidze_xyz` ?

Thanks!

**Comment by palkan** [comment]
> How can I check for an out of date logidze_xyz ?

Could you, please, the contents of the latest `logidze_install` or `logidze_update_x` migration?

**Comment by ianpetzer** [comment]
Thanks so much @palkan 

I ran the following:

    rails generate logidze:install --update

I can confirm that responsible_id now being set. Didn't realise there was an upgrade migration!
