### ISSUE TITLE
Feature request: `touch_log_data!`

### ISSUE THREAD

**Issue by archonic** [palkan/logidze#153]
I've developed an autosave feature that could make use of the method discussed in #94. It would also be nice to clean up old methods which make a whitespace change to ensure that `log_data` reflects the current state of attributes after making changes with `without_logging`.

`restore_log_data!` is an active record method which we don't want to overwrite. `touch_log_data!` makes sense to me. This would insert a new entry in `log_data` with current attributes without relying on `@model.changes` being populated for diff calculation.

**Comment by palkan** [comment]
So, these are my current thoughts on the possible implementation:

- First, let's call this method `fixup_log_data!` and provide a relation variant as well, i.e.:

```ruby
post = Post.first

# call it on a single record
post.fixup_log_data!

# or on a relation (to allow mass fixup)
Post.where(id: ids).fixup_log_data!
```

- This method should re-use the existing `logidze_xxx` PostgresQL functions as much as possible, though we might need a new top-level method; the query would look like:

```sql
update posts set log_data = logidze_some_function(posts.*) where ...
```

**NOTE:** This method shouldn't activate the existing triggers (probably, wrapping with `Logidze.without_logging` Ruby-side is an optimal solution).
Also, this method should take into account metadata.

- Ideally, we want the newly added log entry to be a partial diff, not a full snapshot. Theoretically, that's possible, though could be a bit complicated.

**Comment by palkan** [comment]
So, I ended up with a bit different feature:

```ruby
record = Model.find(params[:id])

Logidze.without_logging do
  # perform multiple write operations with record
end

Logidze.with_full_snapshot do
  record.touch
end
```

Adding new pg function would be costly, since we need to take into account all the various parameters (filtering, timestamp columns, etc.). For now, let's keep everything in the trigger.

**Comment by archonic** [comment]
Awesome, I'll check this out soon (I hope!)
