### ISSUE TITLE
README doesn't match current version 0.12

### ISSUE THREAD

**Issue by artplan1** [palkan/logidze#161]
Hey,
I wanted to use `update migration` with `except` filter to update trigger to exclude some fields, but it didn't work (it generated migration without this filter). After investigation I found that I should use `blacklist` instead of `except` for the latest released version (0.12). Maybe it will be good to add note about this in readme so docs matches latest release?

Thanks for this gem!

**Comment by palkan** [comment]
> Maybe it will be good to add note about this in readme so docs matches latest release?

Definitely! Added a note to the readme!.
Thanks!
