### ISSUE TITLE
LoadError: cannot load such file -- logidze/migration

### ISSUE THREAD

**Issue by artplan1** [palkan/logidze#166]
### Tell us about your environment

**Ruby Version:** 2.7.1

**Rails Version:** master

**PostgreSQL Version:** 12

**Logidze Version:** master

### What did you do?

1. installed logidze in project using latest released version
2. upgraded logidze to master branch
3. tried to deploy to stack (run all migrations after step 1)

### What did you expect to happen?

successfully migrate

### What actually happened?

`migration` was removed in https://github.com/palkan/logidze/commit/836e72c1a1ce8ae277bbc7ccf5d5f356a5548dbc#diff-252a9c5a42ca5f65066e6477864b753f, but it is required in migrations generated using latest released version

This is just fyi, I assume it's pretty rare case, so I just manually updated migration to template from master

**Comment by palkan** [comment]
Thanks for reporting!

Added upgrade notes to Readme: https://github.com/palkan/logidze#upgrading-from-0x-to-10-edge
