### ISSUE TITLE
PG::UndefinedFunction: ERROR:  function logidze_logger() does not exist

### ISSUE THREAD

**Issue by kinsomicrote** [palkan/logidze#172]
### Tell us about your environment

**Ruby Version:** 2.7.1

**Rails Version:** 6.0.3

**PostgreSQL Version:** 11

**Logidze Version:** 1.0.0

### What did you do?

Attempted to deploy the app to the server. I am making use of Digitalocean via hatchbox.io

### What did you expect to happen?

I expected that the migrations would run smoothly.

### What actually happened?

I got the error `PG::UndefinedFunction: ERROR:  function logidze_logger() does not exist`. I should add that I pushed the generated migrations and the SQL files which contained the necessary data for logidze to work.

Any pointers on how to resolve this or what I could be doing wrong?

**Comment by palkan** [comment]
>  got the error PG::UndefinedFunction: ERROR: function logidze_logger() does not exist

Does this happen during `rake db:migrate`? Which migration causes?
Which new migrations do you have for this deployment? (could your run `db:migrate:status` before `db:migrate`?)

**Comment by kinsomicrote** [comment]
Yes, it happens on `rake db:migrate`.

It's caused by this migration.
```
class AddLogidzeToListings < ActiveRecord::Migration[5.0]
  def change
    add_column :listings, :log_data, :jsonb

    reversible do |dir|
      dir.up do
        create_trigger :logidze_on_listings, on: :listings
      end

      dir.down do
        execute "DROP TRIGGER IF EXISTS logidze_on_listings on listings;"
      end
    end
  end
end
```

I ran `rake db:migrate:status` before `rake db:migrate` and here is what the result looks like.
```
Status   Migration ID    Migration Name
--------------------------------------------------
   up     20200602173559  Devise token auth create users
   up     20200602202046  Remove nickname and image column from users
   up     20200613193952  Add trackable columns to users
   up     20200614150342  Create profiles
   up     20200725111358  Create active storage tablesactive storage
   up     20200725174552  Add indexes to profiles
   up     20200726080541  Edit bvn on profiles
   up     20200808122445  Add slug to profiles
   up     20200808195753  Create bank accounts
   up     20200815130859  Create addresses
   up     20200815173627  Create categories
   up     20200815174608  Add lower index to categories
   up     20200816092251  Add role column to users
   up     20200816092718  Edit name column in users
   up     20200816094139  Remove bvn unique index in profiles
   up     20200822181110  Create listings
   up     20200822193042  Create friendly id slugs
   up     20200912191211  Create rentals
   up     20200919215637  Add unique index on rental reference code
   up     20200920120212  Create rental dates
   up     20201123152347  Add slug to categories
   up     20201123171510  Add document type to profiles
   up     20201124113722  Remove document type from profiles
   up     20201124114924  Create profile documents
   up     20201128163658  Enable hstore
  down    20201128164630  Add logidze to listings
  down    20201128165803  Logidze install
  down    20201209212528  Remove null constraint on profile phone number
  down    20201224160153  Add phone number to users
  down    20201224162334  Remove phone number from profiles
  down    20201227134410  Remove city from addresses
  down    20201229175521  Add validated phone to profiles
  down    20201231210717  Create recent listing references
  down    20210103142053  Add phone number to profiles
  down    20210103165337  Remove phone number from users
```

**Comment by palkan** [comment]
>  down    20201128164630  Add logidze to listings
  down    20201128165803  Logidze install
  
That's the problem: the order of migrations is incorrect. Change the timestamp for Logidze install to be lower than Add logidze to listings.

**Comment by kinsomicrote** [comment]
Oh, got it. Let me try that now. Thanks.

**Comment by kinsomicrote** [comment]
I did that an ran into the same issue. I looked into the Logidze Install migration and saw that it was bare like this.
```
class LogidzeInstall < ActiveRecord::Migration[5.0]
  def change
  end
end
```
Is that how it's supposed to be?

**Comment by kinsomicrote** [comment]
Please, is this a valid example of what it's supposed to look like?
https://gist.github.com/kinsomicrote/9c2954decdcf3d7aa744e22b96f02239

**Comment by palkan** [comment]
> is this a valid example of what it's supposed to look like?

It doesn't match your Logidze version, it's for the previous version, not 1.0

**Comment by kinsomicrote** [comment]
> > is this a valid example of what it's supposed to look like?
> 
> It doesn't match your Logidze version, it's for the previous version, not 1.0

Oh, okay. What do you suggest I do or what's the solution?

**Comment by palkan** [comment]
> What do you suggest I do or what's the solution?

Drop both Logidze migrations, run `bundle exec rails g logidze:install` and `bundle exec rails g logidize:model Listing` again.

I'd also recommend installing `fx` gem to make migrations more readable.

**Comment by kinsomicrote** [comment]
Great, I'll do those, thanks.
I already have the `fx` gem.

**Comment by kinsomicrote** [comment]
@palkan QQ: is the migration file supposed to be empty. I dropped the old migrations, ran `bundle exec rails g logidze:install` and the new migration looks like this.
```
class LogidzeInstall < ActiveRecord::Migration[5.0]
  def change
  end
end
```

I just want to confirm that it's correct.

**Comment by kinsomicrote** [comment]
Or could this be it because I am making use of fx gem?

<img width="326" alt="Screenshot 2021-01-06 at 14 10 19" src="https://user-images.githubusercontent.com/6418930/103771930-f38dc300-5028-11eb-84e9-76f3a9d6e3dc.png">

**Comment by palkan** [comment]
> Or could this be it because I am making use of fx gem?

Yeah, that happens when you already have matching sql files; try removing all `functions/logidze_*`, `triggers/logidze_*`, logidze migrations, and run generator again.

**Comment by kinsomicrote** [comment]
Alright.

**Comment by kinsomicrote** [comment]
That worked. Thanks for your help @palkan
