### ISSUE TITLE
For discussion: mysql adapter

### ISSUE THREAD

**Issue by charlie-wasp** [palkan/logidze#18]
Hi,

I wonder, what prevents logidze from mysql support? Is there some technical reasons, or it's just a lack of time and no need of it right now?

I think, with mysql support this gem can address much more people's problems.

**Comment by palkan** [comment]
Hey, @charlie-wasp !

> .. lack of time and no need of it ...

Actually, both)

Another reason is a heavy usage of PostgreSQL-specific jsonb/hstore functionality.
I'm not familiar with MySQL too much, but I've never heard about anything similar.

**Comment by charlie-wasp** [comment]
@palkan I would like to investigate this, if you don't mind. I know, that mysql has json type, but it's all I know, unfortunately :)

**Comment by palkan** [comment]
Great! Waiting for your PRs)

**Comment by charlie-wasp** [comment]
Little update:

At the moment, I hit the wall. In MySQL triggers `NEW` and `OLD` variables are completely static, it seems to be impossible to access columns dynamically (not saying about cool `NEW.*` thing). But I am not stopping (yet), I'll try to find workarounds, if they are possible.

**Comment by rafaelss95** [comment]
Hello, is there any update to support mysql?

**Comment by charlie-wasp** [comment]
@rafaelss95 unfortunately, no updates. I've quitted research, because at the moment it seems impossible to integrate mysql without breaking gem design. So if you or anyone can help here, you're welcome :)
