### ISSUE TITLE
Remove Rails meta-gem dependency in favor of more specific dependency? Railties?

### ISSUE THREAD

**Issue by bf4** [palkan/logidze#184]
Would you be up for PR to remove the strict gem dependency on the Rails meta-gem, and perhaps replace it with railties and activerecord?  As it is, adding this gem to our Gemfile requires us to install action_cable, etc which we otherwise wouldn't need to install.

**Comment by palkan** [comment]
> Would you be up for PR to remove the strict gem dependency on the Rails meta-gem, and perhaps replace it with railties and activerecord?

Yes, please!

**Comment by bf4** [comment]
Done https://github.com/palkan/logidze/pull/186
