### ISSUE TITLE
Retrieving latest version even if last version is the current version

### ISSUE THREAD

**Issue by cirdes** [palkan/logidze#185]
I'm using logidze 1.0 however I need to take the snapshot after a couple of users approve that changes. To do so, I didn't create the update trigger and I'm using "my_model.create_logidze_snapshot!" to manually create the version after the approval process. That part is working fine. 

My problem is when I make changes to record and I want to retrieve version 1 that is different from the current saved model. The [at_version](https://github.com/palkan/logidze/blob/2927dd22e237d327b15ee2422bce1042106cbd9f/lib/logidze/model.rb#L131) method checks if log_data.version == version and because I only have 1 version and I want to retrieve that version it will return self(the record) instead of the version that I want.

For exemple:

My current persisted model:
Post
title='New Title'

my last version:
version 01
title='Old Title' 

If I use post.at(version: 1) I will retrieve the current post(title='New Title') instead of title='Old title'

I would like to change that behavior and always retrieve the version passed as param instead of self, it makes sense for you? If so I can try to open a PR.

**Comment by palkan** [comment]
> There is an easy way to add a new entry instead of reset?

Not yet. But your use case looks viable, we should probably add an ability to append a full snapshot manually.

As of the original question, I think, we may consider a more accurate algorithm of detecting whether `self` equals to the latest version (maybe, using timestamp column). We still want to return self if it corresponds to the latest log entry, we just need a better way to detect whether it is or not.

**Comment by cirdes** [comment]
Should I try to create a PR to use timestamp column to detect if it should return self instead of latest version?

> Not yet. But your use case looks viable, we should probably add an ability to append a full snapshot manually.

The workaround I found was to add a new column `logidze_version` and change the trigger to only run when logidze_version is incremented. It would be better if I had a method like `create_logidze_snapshot` but it is working like I want. When I want a new snapshot I just need to increment logidze_version.

```
class AddLogidzeToPosts < ActiveRecord::Migration[6.1]
  def change
    add_column :posts, :log_data, :jsonb
    add_column :posts,
    :logidze_version,
    :integer,
    null: false,
    default: 0

    reversible do |dir|
      dir.up do
        execute <<~SQL
          CREATE TRIGGER logidze_on_posts
          BEFORE UPDATE OR INSERT ON posts FOR EACH ROW
          WHEN (OLD.logidze_version != NEW.logidze_version)
          -- Parameters: history_size_limit (integer), timestamp_column (text), filtered_columns (text[]),
          -- include_columns (boolean), debounce_time_ms (integer)
          EXECUTE PROCEDURE logidze_logger(null, 'updated_at');

        SQL
      end

      dir.down do
        execute "DROP TRIGGER IF EXISTS logidze_on_posts on posts;"
      end
    end
  end
end
```

**Comment by palkan** [comment]
We were actually thinking about allowing to have trigger off by default and enable it explicitly (`Logidze.enabled { ... }`), which would provide the same behaviour as in the example above. However, there are some concerns regarding the consistency: what should we store in the logs? Full snapshots every time? Or calculate diffs somehow? That could make the methods like `#diff_from` return incorrect results (because the current record state could be not committed to the log yet).

/cc @skryukov

**Comment by skryukov** [comment]
Yep, unfortunately, a lot of code depends on the fact that the last log is the current version of the record.

What if we will add something like `Logidze.append { ... }`. Logidze will merge all operations inside this block to the latest version. This way latest version will be a "draft", and versions n+1 will represent "saved" versions.

**Comment by cirdes** [comment]
I realized that I was trying to do too much with versioning. So I decide to change my strategy. Thanks for supporting me.
