### ISSUE TITLE
Are race conditions an issue?

### ISSUE THREAD

**Issue by NullVoxPopuli** [palkan/logidze#22]
If I have two processes, one which intends to update the log_data (model b), and one wants to disable logging (model a), would this scenario be possible:

disable logging to save a
start saving b
start saving a
finish saving b
finish saving a
re-enable logging after saving a

b's log wasn't updated?

**Comment by palkan** [comment]
Logging is disabled only for the current connection (we use postgres _session variables_).

In its turn, ActiveRecord uses different connections for different threads.

Thus there can not be race conditions. Unless you don't force ActiveRecord to use the same connection between threads, of course)

**Comment by NullVoxPopuli** [comment]
excellent, thank you!
