### ISSUE TITLE
docs: logdize cannot set session meta data when using a connection pool

### ISSUE THREAD

**Issue by bf4** [palkan/logidze#239]
I was chatting with someone about logidze and they pointed out that setting fields like the responsible id cannot be done in (most?) connection pooling environments.  Since we considered connection pooling but did't consider it's effect on logidze, I thought I'd mention here.

**Comment by palkan** [comment]
Yeah, meta is set per session; so, if you set meta outside of a transaction, there can be a race condition. 

Added a note to the documentation.

Probably, we can add support for connection pooling by watching for all transactions opened and closed and re-populating the metadata.
