### ISSUE TITLE
Not possible to use latest logidze and anyway_config with Ruby 3.3.0

### ISSUE THREAD

**Issue by yenshirak** [palkan/logidze#243]
The current 1.2.3 version has a `ruby-next-core (~> 0.9)` dependency which conflicts with the anyway_config 2.6.2 `ruby-next-core (~> 1.0)` dependency so currently it isn't possible to use the latest version of both gems with Ruby 3.3.0.

I see that the `ruby-next-core (~> 0.9)` dependency has been removed from master. Is there a date for the next release?

**Comment by palkan** [comment]
Thanks for reporting! Released v1.3.0
