### ISSUE TITLE
Add user_id who changed

### ISSUE THREAD

**Issue by khelal** [palkan/logidze#4]
Great gem! Is there a way to add the user_id that is responsible for the change, via current_user is present?

**Comment by palkan** [comment]
Currently, there is no such functionality. However, we are going to add it (although it is a little bit tricky due to Logidze calculates changes DB-size).

**Comment by khelal** [comment]
Great, looking forward to it so that we can replace our papertrail with this much cleaner implementation.

**Comment by palkan** [comment]
@khelal Check [this](https://github.com/palkan/logidze#track-responsibility-aka-whodunnit) out!

**Comment by khelal** [comment]
Excellent!

On Monday, 11 July 2016, Vladimir Dementyev <notifications@github.com>
wrote:

> @khelal <https://github.com/khelal> Check this
> <https://github.com/palkan/logidze#track-responsibility-aka-whodunnit>
> out!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/palkan/logidze/issues/4#issuecomment-231732208>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAC0fUeFxwNbRXeFOVqTO9B0VfIJWHsBks5qUkOIgaJpZM4JBZcr>
> .
>


-- 
--
*Karim HELAL*
CoFounder & CEO @ ProTenders.com <http://www.protenders.com/>
Taking the Risk out of Construction Bidding

*CAN:* +1.438.765.6886  |  *UAE:* +971.50.641.7143  |  *USA:*
 +1.650.265.7532

Trusted by hundreds of companies to process over $12.4 billion of bids
since 2009.
Voted Best eCommerce Solution by the WSA Awards, MENA ICT & Internet Awards
Follow us on twitter <http://www.twitter.com/monaqasat>  |  facebook
<http://www.facebook.com/monaqasat>  |  our blog
<http://blog.monaqasat.com/>
