### ISSUE TITLE
Support for ruby >2.1

### ISSUE THREAD

**Issue by ziaulrehman40** [palkan/logidze#47]
Is there **any plan and/or roadmap to support ruby >2.1?** As requirements states **only ~>2.1**
Is this because there are some hard dependencies on ruby 2.1?

Actually, I am using **latest ruby patch level 2.4.1** and I am looking for a logging mechanism. Logidze sounds cooler than others. But this specific requirement is a road block for me(and for others too of-course).

Let me know if I can help in any form for this issue.

**Comment by palkan** [comment]
Hi, @ziaulrehman40!

Of course, you can use it with 2.4.1) Actually, `~> 2.1` means `>= 2.1, < 3.0`.

**Comment by ziaulrehman40** [comment]
Oh, my bad!
I though it meant >=2.1 and <2.2
