### ISSUE TITLE
Trying to get Logidze working

### ISSUE THREAD

**Issue by SimonDKnight** [palkan/logidze#50]
Hi, I am having some issues getting Logidze working. I have followed your install instructions and whenever I try to create I get the following error

```
PG::UndefinedFunction - ERROR:  function to_jsonb(positions) does not exist
LINE 1: SELECT logidze_snapshot(to_jsonb(NEW.*), ts_column, columns_...
                                ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
QUERY:  SELECT logidze_snapshot(to_jsonb(NEW.*), ts_column, columns_blacklist)
CONTEXT:  PL/pgSQL function logidze_logger() line 20 at assignment
```

Any ideas?

I am using the Apartment gem which is tenanting my customers using postgres schemas, perhaps this is the problem?

**Comment by palkan** [comment]
Hi!

Which PostgreSQL version do you use?

**Comment by palkan** [comment]
@SimonDKnight ping)

**Comment by palkan** [comment]
Closed as stale

**Comment by ydakuka** [comment]
I got the same error.
```bash
ydakuka@Yauheni-Work:~/virtual_box/project$ psql --version
psql (PostgreSQL) 9.5.10
```

```bash
ydakuka@Yauheni-Work:~/virtual_box/project.app$ rails db:migrate
== 20171230234326 AddLogidzeToUsers: migrating ================================
-- add_column(:users, :log_data, :jsonb)
   -> 0.0008s
-- execute("      CREATE TRIGGER logidze_on_users\n      BEFORE UPDATE OR INSERT ON users FOR EACH ROW\n      WHEN (coalesce(current_setting('logidze.disabled'), '') <> 'on')\n      EXECUTE PROCEDURE logidze_logger(null, 'updated_at');\n")
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedFunction: ERROR:  function logidze_logger() does not exist
:       CREATE TRIGGER logidze_on_users
      BEFORE UPDATE OR INSERT ON users FOR EACH ROW
      WHEN (coalesce(current_setting('logidze.disabled'), '') <> 'on')
      EXECUTE PROCEDURE logidze_logger(null, 'updated_at');
```

**Comment by palkan** [comment]
@ydakuka this is not the same; your error says that there is no `logidze_logger` function. Looks like you haven't _initialized_ Logidze;  you have to run `rails generate logidze:install`, which creates a migration with all necessary functions. Note: that migration should run before any other Logidze-related migration.

**Comment by derekgstevens** [comment]
I hope you don't mind me commenting on a closed issue, but I'm getting the same issue as ydakuka above, but while using the apartment gem like SimonGKnight. It appears that my initial logidze migration isn't being run across the pg schemas I have, which is causing it to throw the 'function not found' error. 

Any ideas?

**Comment by ydakuka** [comment]
Do you have more than one 'logidze' migration?

Try `rails db:reset db:migrate`.

**Comment by palkan** [comment]
Hi @derekgstevens!

Check [this section](https://github.com/influitive/apartment#installing-extensions-into-persistent-schemas) from the `apartment` Readme.

It explains how to enhance schemas with raw SQL (that's exactly what we need to install Logidze).

**Comment by archonic** [comment]
@palkan Is raw SQL required when using Apartment + Logidze or do the previous instructions (steps 1-3) work as well?

**Comment by palkan** [comment]
@archonic Looks like your schema doesn't have `hstore` extension installed. Do you have a `xxx_enable_hstore.rb` migration? And `CREATE EXTENSION IF NOT EXISTS HSTORE` in your `structure.sql` (if any)?

**Comment by archonic** [comment]
I've had the error above when I had the xxx_enable_hstore.rb migration. I removed it since I figured it wasn't required when this is in my schema.rb.
```
enable_extension "hstore"
enable_extension "plpgsql"
enable_extension "uuid-ossp"
```
I'm not using a structure.sql file.

Interestingly it seems to have not installed `uuid-ossp`.
```
\dx
                           List of installed extensions
  Name   | Version |   Schema   |                   Description                    
---------+---------+------------+--------------------------------------------------
 hstore  | 1.4     | public     | data type for storing sets of (key, value) pairs
 plpgsql | 1.0     | pg_catalog | PL/pgSQL procedural language
(2 rows)
```

**Comment by archonic** [comment]
I have a minimal logidze + apartment application here which has the same issue:
https://github.com/archonic/logidze-apartment

If you create then update a document in the public schema, logidze will populate `log_data` and everything is fine. If you create then update a document within a schema, it's not populated. I believe that's because the trigger isn't available within that schema, which is why apartment mentions the `schema_search_path` and the `shared_extensions` schema which holds extensions and triggers. Am I understanding that correctly?

**Comment by palkan** [comment]
@archonic Thanks for sharing an examples app! I made it work, here is a PR with a description: https://github.com/archonic/logidze-apartment/pull/1

**Comment by archonic** [comment]
Beauty! 🙌 Thanks very much. Let me know if I can buy you a beer 😄

**Comment by palkan** [comment]
> Let me know if I can buy you a beer

😺 Do you deliver to Moscow?))

**Comment by archonic** [comment]
https://twitter.com/palkan_tula/status/996002315701284865

Totally agree. Sounds like an idea for an app. How about an email money transfer to the email on your profile?

**Comment by palkan** [comment]
Hey @archonic! Hope you're doing well.

It looks like `logidze-apartment` repo is no longer available (and my fork as well). And I can't remember what was the fix 🙂

Could you please remind me?

**Comment by archonic** [comment]
Hey! Now I wish I hadn't deleted it. I don't have it locally either, but the fix is in another repo. Let me see if I can find it.

**Comment by archonic** [comment]
https://github.com/archonic/logidze-apartment

I'm not sure where the fix was but that's an example that can safely run `rails db:reset`.

**Comment by palkan** [comment]
@archonic  Thanks!
