### ISSUE TITLE
Empty Entries With Black Listing

### ISSUE THREAD

**Issue by economysizegeek** [palkan/logidze#53]
I track a position in a list and the status of data display in a table row. 

` execute <<-SQL
      CREATE TRIGGER logidze_on_brokerage_transactions
      BEFORE UPDATE OR INSERT ON brokerage_transactions FOR EACH ROW
      WHEN (coalesce(#{current_setting('logidze.disabled')}, '') <> 'on')
      EXECUTE PROCEDURE logidze_logger(100, 'updated_at', '{created_at, position, stale}');
    SQL`

The position and stale get updated a lot - and they don't actually matter to the audit.  I ended up with a bunch of records that just have the updated_at as the changed field.  I then change it to:
` EXECUTE PROCEDURE logidze_logger(100, '', '{created_at, position, updated_at, stale}');`

Now I have a bunch of change entries with no entries in them.  Basically I'm trying to only store changes if there is a change in a field that isn't created_at, position or stale.   What should it look like?

**Comment by palkan** [comment]
> I then change it to:
`EXECUTE PROCEDURE logidze_logger(100, '', '{created_at, position, updated_at, stale}');`

Looks good to me. Except from the second argument: it should be either 'updated_at' (if you want to use `updated_at` column value as a log timestamp) or `null` (if you want to rely on DB current time as a log timestamp).

> Now I have a bunch of change entries with no entries in them. 

Looks like a bug: if everything is filtered out we still add a log entry. @charlie-wasp Could you, please, take a look?

**Comment by economysizegeek** [comment]
1. So should I change it to this: 
`EXECUTE PROCEDURE logidze_logger(100, null, '{created_at, position, updated_at, stale}');`
2. Let me know if there is anything I can contribute to help sort the problem. I assumed I was just doing something wrong :) I want to track most changes but not all of them.

**Comment by economysizegeek** [comment]
I made the null change and it it still generating empty change versions.  

` {"c"=>{}, "v"=>2, "ts"=>1514993038238}, {"c"=>{}, "v"=>3, "ts"=>1514993038268}, {"c"=>{"closed_at"=>"2018-03-03 15:24:52.146939"}, "v"=>4, "ts"=>1514993094375}, {"c"=>{}, "v"=>5, "ts"=>1514993100172}, {"c"=>{}, "v"=>6, "ts"=>1514993100204}], "v"=>6}`

**Comment by palkan** [comment]
Fixed by #55 and released as 0.6.2
