### ISSUE TITLE
Trouble loading active_model/type/value in Rails 5.2.0.beta2

### ISSUE THREAD

**Issue by MatiasFMolinari** [palkan/logidze#54]
**Issue:** I'm getting this error when I try to load the logidze gem in Rails 5.2.0.beta2.

**Error:**

```
There was an error while trying to load the gem 'logidze'. (Bundler::GemRequireError)
Gem Load Error is: uninitialized constant ActiveModel::Type::Value
```

**Where it happens:** ```/lib/logidze/history/type.rb:2```

**What solved it for me:**

```ruby
ActiveSupport.on_load(:active_record) do
  require 'active_model/type/value'
end
```

**Link:** https://github.com/MatiasFMolinari/logidze/blob/df9e885078517b3107e817979be1be50d2c56c75/lib/logidze/history/type.rb#L2

**Source:**
I don't fully understand how the loading changed in this new rails version. I stumbled upon the solution on this commit: https://github.com/iaankrynauw/paranoia/commit/49b9e68ee79d8a8e5fa04add1e93b9d69ccf9315

**Comment by palkan** [comment]
Thanks for the report!

Fixed by https://github.com/palkan/logidze/commit/5d593d1ac790d97b47ed33c7aac5a0896aa892dc and released as 0.6.1.
