### ISSUE TITLE
Unable to load version using ActiveRecord `updated_at`

### ISSUE THREAD

**Issue by jasonjho** [palkan/logidze#72]
If I understood the docs, the timestamp is derived from the `updated_at` timestamp at the record level. In my case, I have these set by ActiveRecord, so they are always available. 

If I try to load a version `at(time: <record.updated_at>)`, I am getting back `nil`. Somehow, the timestamps seem to be off by 1 millisecond after inspecting `log_data`. Simply adding 1 to the timestamp will yield the expected result, but I feel I am missing something here.  

I simply want to grab the version based on the recorded `updated_time`. Any tips would be appreciated, thanks!

**Comment by jasonjho** [comment]
I'm not too familiar w/ DateTime parsing, but might there be a rounding issue here?

https://github.com/palkan/logidze/blob/master/lib/logidze/model.rb#L257

**Comment by palkan** [comment]
Sorry for a long reply.

>  the timestamp is derived from the updated_at timestamp at the record level

That's only true if you have provided the `timestamp_column` to the `logidze:model` generator. How does your Logidze migration for the table look like?

**Comment by palkan** [comment]
> Does this mean we have the right setting?

Yep, looks good.

Could you, please, provide an example of SQL rows with wrong timestamps?
