### ISSUE TITLE
[Question] why is there `&` in `Logidze.with_responsible(current_user&.id, &block)`

### ISSUE THREAD

**Issue by zocoi** [palkan/logidze#86]
In the example of add responsible id to the changelog in README:

```
  def set_logidze_responsible(&block)
    Logidze.with_responsible(current_user&.id, &block)
  end
```

I haven't seen the `current_user&.id` used before. What's the difference between it and the normal `current_user.id`?

**Comment by zocoi** [comment]
ah nvm, I found this article: https://stackoverflow.com/questions/36812647/what-does-ampersand-dot-mean-in-ruby

**Comment by palkan** [comment]
Sounds like solved then 🙂
