### ISSUE TITLE
Using Logidze with an unconventional project structure

### ISSUE THREAD

**Issue by bdiesel** [palkan/logidze#88]
I've installed logidze in a project without a conventional structure and I'm receiving an exception

```
class Project < Shared::ApplicationRecord
    has_logidze

```
**undefined local variable or method `has_logidze' for Clients::Project(Table doesn't exist):Class** 

when I move has_logidze to a line after the the table name is set in the model I receive a slightly different exception

```
class Project < Shared::ApplicationRecord
    self.table_name = 'projects'
    has_logidze

```
**undefined local variable or method `has_logidze' for #<Class:0x00007fbb160a04c8>**

**Comment by palkan** [comment]
What is the parent class for `Shared::ApplicationRecord`?

Is this a Rails app or you're using ActiveRecord without Rails?

A quick fix could be is to add this line to `Shared::ApplicationRecord`:

```ruby
include Logidze::HasLogidze
```

**Comment by bdiesel** [comment]
- Parent class for application Shared::ApplicationRecord  is ActiveRecord::Base, this class just sets abstract_class to true

- This is a rails app we just have a few rails apps running out of the same project 

- Adding include Logidze::HasLogidze to the Shared::ApplicationRecord is giving me an error **uninitialized constant Shared::ApplicationRecord::Logidze**  but I think this is the right idea logdize isn't loading properly due to our project structure.  I'll look further into this.

- Thank you!  Looking forward to working with logidze!

**Comment by bdiesel** [comment]
I believe this issue was caused by spring not reloading Logidze.  Thank you again for your assistance!
