### ISSUE TITLE
redoing with append breaks carrierwave

### ISSUE THREAD

**Issue by fauno** [palkan/logidze#90]
Hi, I haven't been able to debug much yet but wanted to report this.  I enabled logidze for a model with a carrierwave field.  I'm showing a table with all revisions and providing a button to undo them, so I wanted to use `append: true`.

While `model.undo!` and `model.redo!` work correctly, `model.redo! append: true` makes carrierwave fail.  Apparently it's re-running the upload process without a file attached to it, so it can't read any of it's attributes (in my particular setup if can't find the extension to create the filename).

I'll update this issue with my findings :)

**Comment by palkan** [comment]
Hi!

> `model.redo! append: true`

Do you mean `model.undo!`? We do not have `append` option for `redo`.

>  makes carrierwave fail

What is the error message?

Could you, please, provide a data log (i.e. which changes do you want to apply)

**Comment by fauno** [comment]
Sorry for the delay.  Yes, I meant `undo! append:true`, but I got the same error with carrierwave by doing some other stuff so it may not be related to logidze.  I'll come back with more details

**Comment by palkan** [comment]
Hey @fauno!

Did you resolve the issue?

**Comment by fauno** [comment]
hi! sorry, i had to put this project on hold but i may retake it soon...

-- 
P)

**Comment by palkan** [comment]
OK. Closing for now. Feel free to ping me to re-open if you hit this problem again.
