### ISSUE TITLE
Compress changes into the last version on demand

### ISSUE THREAD

**Issue by archonic** [palkan/logidze#94]
Thanks for the speedy work on #93!

The recent debounce changes are welcome, but I'm wondering if we could add a feature to do this on demand. I have a background job which generates a table of contents for a document after it's been saved. Since the table of contents links to headers within the document, this job needs to modify the document itself. Currently, the changes this job makes to the document are ignored by Logidze, but it would be better if I could tell Logidze to lump a set of changes into the most recent version in log_data, in a block. It would also aid in generating reasonable history when importing a document.

**Comment by palkan** [comment]
@archonic  Your scenario looks a little bit different from debouncing, 'cause you don't want to compress changes for the specified period of time but for some _unit of work_. So it should be smth like:

```ruby
# wrap execution in a block
Logidze.with_log_compression do
  generate_table_of_contents
end
``` 

Independently on how many changes have been made within a block, we only generate one log entry in `log_data` for **all Logidze-tracked records**.

Is that right?

**Comment by archonic** [comment]
If everything within a block was compressed into one log entry regardless of how many transactions there were, that would help in the case of imports, but not in the case of the table of contents, since it occurs in a background job. If Logidze works in an after_commit hook, I think I could just use an `ActiveRecord::Base.transaction do` block to achieve the same thing (right?).

I'm looking for the changes within a `Logidze.with_log_compression` block to "pretend" as if the changes made within that block were made on the most recent log entry.

Right now, with `Logidze.without_logging` it has the table of contents job changes appear on the next version. So a user saves the document with new headers, then the job runs and assigns those headers a unique ID, then the user edits the document again. The log_data will look as if the user's second edit included the changes that were done in the table of contents job. It would be better if the changes associated with that job were lumped into the edit that was responsible for triggering the background job.

**Comment by palkan** [comment]
> The log_data will look as if the user's second edit included the changes that were done in the table of contents job.

That seems strange. Every log entry is the diff between the current record's state and the new one; it doesn't take into account the changes taken within `without_logging`.

>  If the Logidze functions work on a per-transaction basis

Nope. Logidze work on _per-query_ basis, i.e. each `UPDATE` generates a new log entry even within the same transaction.

**Comment by archonic** [comment]
> Every log entry is the diff between the current record's state and the new one; it doesn't take into account the changes taken within without_logging.

Isn't every log entry the snapshot of tracked attributes?

I've done some console tests to demonstrate:

```
doc = Document.new(account_id: 1, owner: User.first, name: "Log Test", description: "Just testing.", contents: "<h1>Header 1</h1><p>Initial content.</p>")

# background job runs and populates header ID without logging
doc.reload.contents
"<h1 id=\"ecb132\">Header 1</h1><p>Initial content.</p>"

# ID isn't present in log_data (as expected)
doc.reload.log_data.data["h"]
{
  "c"=>{
    "name"=>"Log Test",
    "contents"=>"<h1>Header 1</h1><p>Initial content.</p>",
    "owner_id"=>1,
    "updated_at"=>"2018-10-29T04:00:30.005991",
    "description"=>"Just testing."
  },
  "v"=>1,
  "ts"=>1540785630006
}

# Simulating a user editing contents
doc.contents << "<p>Addition</p>"
doc.save
doc.reload.log_data.data["h"]
{
  "c"=>{
    "name"=>"Log Test", 
    "contents"=>"<h1>Header 1</h1><p>Initial content.</p>", 
    "owner_id"=>1, 
    "updated_at"=>"2018-10-29T04:07:24.221416", 
    "description"=>"Just testing."
  }, 
  "v"=>1, 
  "ts"=>1540786044221
}, 
{
  "c"=>{
    "contents"=>"<h1 id=\"ecb132\">Header 1</h1><p>Initial content.</p><p>Addition</p>", 
    "updated_at"=>"2018-10-29 04:09:20.117371"
  }, 
  "v"=>2, 
  "ts"=>1540786160117
}

# With the above change, the diff now includes contents that changed with Logidze.without_logging
{
  "id"=>552,
  "changes"=>{
    "contents"=>{
      "old"=>"<h1>Header 1</h1><p>Initial content.</p>", 
      "new"=>"<h1 id=\"ecb132\">Header 1</h1><p>Initial content.</p><p>Addition</p>"
    },
    "updated_at"=>{
      "old"=>Mon, 29 Oct 2018 04:07:24 UTC +00:00,
      "new"=>Mon, 29 Oct 2018 04:09:20 UTC +00:00
    }
  }
}
```

Everything is behaving as expected, it's just not convenient to have no way to append changes to a log entry. If we had something like `Logidze.append_changes(version: 1) { doc.save }` then background changes could be associated with the version responsible for the background job. Does that make sense?

> Nope. Logidze work on per-query basis, i.e. each UPDATE generates a new log entry even within the same transaction.

Makes sense. I solved my document import log_data issue by doing all import tasks with within a without_logging block, and then calling `@document.touch` after the successful save to create the first log entry version as I wanted it.

**Comment by palkan** [comment]
@archonic Thanks for the example, it's really helpful.

> If we had something like Logidze.append_changes(version: 1) { doc.save }

Unfortunately, we cannot guarantee that there will be only one `UPDATE` statement within a block (even calling `smth.save` could produce multiple statements due to callbacks, in theory).

Another approach could be to _tell_ Logidze to generate a log entry for the current record status:

```ruby
# do something without logging
Logidze.without_logging { doc.do_smth }
# then explicitly call .restore_log_data! to create a log entry with all the changes happened during the block execution
doc.restore_log_data! # adds a new log entry to make sure that the diff is correct
```

**Comment by archonic** [comment]
@palkan Sorry about the super late reply - working on this now.

`doc.restore_log_data!` could be exactly what I'm looking for, but I'm currently making use of the `save_with_contributor` method. Could there be a `restore_log_data_with_contributor!` method?

Saving a document which has callbacks and having an ideal history could look like this:

```
Logidze.without_logging { doc.save }

# callbacks trigger a table of contents job

# inside the table of contents job:

Logidze.without_logging do
  # bunch of stuff
end
Logidze.restore_log_data_with_contributor! user.id
```

**Comment by archonic** [comment]
`restore_log_data!` is a dynamically defined activemodel method. Perhaps you were talking about a hypothetical logidze method which would write a new log entry with the current attribute state?

**Comment by palkan** [comment]
> you were talking about a hypothetical logidze method which would write a new log entry with the current attribute state?

Yep; there is no such method yet

**Comment by archonic** [comment]
Well it certainly has my vote 😃. If you have any suggestions on how to approach it, I can try to submit a PR.

**Comment by archonic** [comment]
I'm not sure how difficult a `touch_log_data` method would be given that all the magic happens in pg triggers, but it think it would be a nice addition. The patch above has been working for me so this can be closed.

**Comment by palkan** [comment]
> I'm not sure how difficult a touch_log_data method would be given that all the magic happens in pg triggers, but I think it would be a nice addition. 

Could you please open a new issue/feature request for this specific features in favor of this one (which I'm closing now)?
